//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetClosePrice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThreeBigBuySell
    {
        public System.DateTime Date { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public int A_Buy { get; set; }
        public int A_Sell { get; set; }
        public int A_Total { get; set; }
        public int B_Buy { get; set; }
        public int B_Sell { get; set; }
        public int B_Total { get; set; }
        public int C_Buy { get; set; }
        public int C_Sell { get; set; }
        public int C_Total { get; set; }
        public int D_Buy { get; set; }
        public int D_Sell { get; set; }
        public int D_Total { get; set; }
        public int CD_Total { get; set; }
        public int Daily_Total { get; set; }
        public string Type { get; set; }
    }
}
